### ISSUE TITLE
Error: Can't send mail - all recipients were rejected: 550 5.7.1 Service unavailable; client [xx.xxx.xxx.xxx] blocked using zen.spamhaus.org

### ISSUE THREAD

**Issue by OfficialCRUGG** [nodemailer/nodemailer#1089] opened 2019-12-28 19:33 UTC
Hello there. I am trying to send Mails, but I always get the following error:
```
(node:60452) UnhandledPromiseRejectionWarning: Error: Can't send mail - all recipients were rejected: 550 5.7.1 Service unavailable; client [xx.xxx.xxx.xxx] blocked using zen.spamhaus.org
    at SMTPConnection._formatError (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:784:19)
    at SMTPConnection._actionRCPT (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:1613:28)
    at SMTPConnection._responseActions.push.str (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:1574:26)
    at SMTPConnection._processResponse (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:942:20)
    at SMTPConnection._onData (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData.chunk (A:\Documents\Git\taigamailing\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
(node:60452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). (rejection id: 1)
(node:60452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I am using the following code:
```js
const nodemailer = require("nodemailer");
const fs = require("fs");

async function sendMail(to, subject, template, contents) {
    let transporter = nodemailer.createTransport({
        host: "xx.xxx.xxx.xxx",
        port: 25,
        secure: false,
        auth: {
            user: "noreply@example.com",
            password: "xxxxxxxxx"
        },
        tls: {
            rejectUnauthorized: false
        }
    });
    transporter.sendMail({
        from: '"name" <noreply@example.com>',
        to,
        subject,
        text: template,
        html: template
    });
}

fs.readFile("./mails/html/newsletter.html", "utf8", (error, data) => {
    if(error) throw error;
    sendMail("<my e-mail>", "Test Mail", data);
});
```
What could cause this and how can I fix it?

**Comment by andris9** [comment] 2020-01-09 08:06
Out of scope for Nodemailer. Your mail server is not accepting emails from your IP. Use a different machine to send out the emails.

**Closed by andris9** 2020-01-09 08:06 UTC

**Comment by MilesTails01** [comment] 2024-06-23 14:49
Its a replicatable issue, so why closing. The problem is not IP.
Had the same problem with the directus mailSend feature,
as they used "Directus <noreply@example.com>" as fallback.
which is not a valid and therefore gets rejected

this line:
`from: '"name" <noreply@example.com>',`

change to:
`from: "your.real@email.com"`
