### ISSUE TITLE
Node mailer gmail service accounts are broken.

### ISSUE THREAD

**Issue by nbroeking** [nodemailer/nodemailer#1170] opened 2020-07-25 16:07 UTC
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [X] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [X] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Node mailers recent documentation suggests support of gmail service accounts. - https://nodemailer.com/smtp/oauth2/#oauth-2lo

However, if I follow the documentation the service accounts method is not able to generate an access token. (Note: This only applies to service accounts. The normal way of creating a username and password work fine. 

Steps to reproduce. 

1.) Log in to console.- https://console.cloud.google.com/
2.) Create a service account under the project.
3.) Create keys for the service account. - https://console.cloud.google.com/iam-admin/serviceaccounts
4.) Create keys for service account - press actions > edit then select add key
5.) Download key file. You will get something like key_file_project.json
6.) Enable gmail api for the service account - https://console.cloud.google.com/apis/api/gmail.googleapis.com/overview
7.) Now write some javascript that uses nodemailer
``` javascript
const nodemailer = require('nodemailer');

const email = 'EMAIL FROM THE KEY FILE WE DOWNLOADED';
const serviceClient = 'CLIENT_ID FROM THE KEY FILE WE DOWNLOADED';
const privateKey = '-----BEGIN PRIVATE KEY----- KEY FROM THE KEY FILE WE DOWNLOADED';

console.log('starting')
const mailTransport = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
      type: 'OAuth2',
      user: email,
      serviceClient: serviceClient,
      privateKey: privateKey,
    },
  });

```
8.) Will crash while creating the transport. 

The error that gets reported to client logs are ```Error: invalid_request```

After adding more logging it looks like the response nodemailer is getting from google is. 

```
{
  error: 'invalid_request',
  error_description: 'Principal must be an email address'
}
```

Thank you for taking a look. If you need any more information please let me know. I am happy to help in anyway I can.

**Comment by andris9** [comment] 2020-07-29 08:35
To be honest I have no idea how to get service accounts working. Everything worked fine about 5 years ago but Google cracked down on Oauth clients that are using "protected" scopes like email and I haven't been able to get a working setup since then. The code is quite basic though, just a simple JWT signing. Maybe something has really changed and the request needs to be signed in some other way, maybe you have invalid configuration, who knows.

Closing for now until it is clear that if this is really a bug on nodemailer side, or a configuration issue where you are using a wrong account or wrong keys or wrong scope.

**Closed by andris9** 2020-07-29 08:35 UTC

**Comment by acalvino4** [comment] 2020-11-20 22:19
I had the exact same issue. Closing this hardly seems like the appropriate move, and is really just sweeping a problem under the rug. Keeping it open would make it more clear that there is work to do here and acknowledge the issue better. Whether the work is in updating documentation on the appropriate configuration, or fixing a bug, there is something to be found out. I'm not necessarily saying any particular person 'owes' this work to us - just saying that closing this when the issue is clearly unsolved is unhelpful.

**Comment by raberana** [comment] 2020-12-14 16:32
I'm actually receiving the _same error response_ with this setup:

```
  const transporter: Mail = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
          type: 'OAuth2',
          user: 'firebase-adminsdk-xxxx@xxxxx.iam.gserviceaccount.com',
          serviceClient: serviceClient,
          privateKey: privateKey,
        }
      });
```

We're you able to solve this issue @nbroeking ?

**Comment by acalvino4** [comment] 2020-12-14 22:25
> I'm actually receiving the _same error response_ with this setup:
> 
> ```
>   const transporter: Mail = nodemailer.createTransport({
>         host: 'smtp.gmail.com',
>         port: 465,
>         secure: true,
>         auth: {
>           type: 'OAuth2',
>           user: 'firebase-adminsdk-xxxx@xxxxx.iam.gserviceaccount.com',
>           serviceClient: serviceClient,
>           privateKey: privateKey,
>         }
>       });
> ```
> 
> Were you able to solve this issue @nbroeking @acalvino4 ?

I was not. I ended up doing it though getting Auth tokens to my personal email rather than through the service account.

**Comment by josemanuelguzman** [comment] 2021-01-01 13:19
Same issue!

**Comment by adrianhajdin** [comment] 2021-01-25 12:27
@nbroeking @acalvino4 @josemanuelguzman @raberana, any luck? I'm experiencing the same issue.

**Comment by josemanuelguzman** [comment] 2021-01-25 14:11
> @nbroeking @acalvino4 @josemanuelguzman @raberana, any luck? I'm experiencing the same issue.

Yes, I follow this instructions usage https://github.com/alexandre-lavoie/strapi-provider-email-gmail-oauth2

**Comment by uc2pac** [comment] 2021-05-29 13:14
@andris9 , it's not working. Can you guys try to figure this out?

**Comment by raptoria** [comment] 2021-06-09 16:35
see https://github.com/nodemailer/nodemailer/issues/871 for a working solution.

**Comment by DrNguyen2525** [comment] 2021-06-21 19:03
> > @nbroeking @acalvino4 @josemanuelguzman @raberana, any luck? I'm experiencing the same issue.
> 
> Yes, I follow this instructions usage https://github.com/alexandre-lavoie/strapi-provider-email-gmail-oauth2

This is normal OAuth2 authentication, not service account authentication.

**Comment by raulbarriga** [comment] 2021-09-07 17:18
> To be honest I have no idea how to get service accounts working. Everything worked fine about 5 years ago but Google cracked down on Oauth clients that are using "protected" scopes like email and I haven't been able to get a working setup since then. The code is quite basic though, just a simple JWT signing. Maybe something has really changed and the request needs to be signed in some other way, maybe you have invalid configuration, who knows.
> 
> Closing for now until it is clear that if this is really a bug on nodemailer side, or a configuration issue where you are using a wrong account or wrong keys or wrong scope.

Well to be fair, their docs do say that you can use a service account with oauth so it should work, at least according to the Nodemailer team. Otherwise, why put in the docs that it works with service accounts. This post is saying they checked that feature 5 years ago and since tech changes quickly, I think it deserves an update in this regard. A latest test run set up for the Oauth2 service account feature would greatly be appreciated.

**Comment by drnguyenn** [comment] 2021-09-08 00:22
@raulbarriga It actually works with a service account, however, delegating authority to the mail service does require a Gooogle Workspace account, not a regular Gmail account. So in common, we cannot use 2LO authentication here.

More information here:
- https://github.com/nodemailer/nodemailer/issues/871#issuecomment-865270091
- https://github.com/googleapis/google-api-nodejs-client/issues/2418
