### ISSUE TITLE
Nodemailer doesn't work on Cloudflare Workers because it uses Built-in node modules without `node:` prefix

### ISSUE THREAD

**Issue by Aloso** [nodemailer/nodemailer#1621] opened 2024-02-09 16:31 UTC
Cloudflare Workers is a serverless JavaScript runtime. It has a Node.js compatibility mode, but it [requires that built-in node modules are imported with the `node:` prefix](https://developers.cloudflare.com/workers/runtime-apis/nodejs/). Because of this, Nodemailer fails to build on Cloudflare Workers.

See [this blog post](https://2ality.com/2021/12/node-protocol-imports.html) about the `node:` prefix, which is the recommended way to import built-in node modules.

Nodemailer requires the `stream`, `fs`, `path`, `url`, `http`, `https`, `zlib`, `net`, `events`, `util`, `dns`, `child_process`, `os`, `tls`, and `crypto` built-in modules. These should be imported with prefix, for example:

```js
const fs = require('node:fs')
```

**Comment by MickL** [comment] 2024-02-10 23:38
Hey @Aloso , why did you close this? I am also deploying on edge functions (Vercel Edge) and it does not work.

**Comment by Aloso** [comment] 2024-02-11 00:12
I figured out a better way, and I read somewhere else that smtp connections from serverless environments aren't allowed anyway. Please correct me if I'm wrong.

I'm using FormSubmit now, it is very convenient and easy to set up.

**Comment by sheecegardezi** [comment] 2024-03-30 00:04
@Aloso alternative approch still does not resolve this issue! Can you please open this issue again it. I am still unable to get it install on cloudflare worker

**Comment by MickL** [comment] 2024-03-30 11:29
I think it will never run on Cloudflare, duplicate of: 
https://github.com/nodemailer/nodemailer/issues/1623

Personally I switched to use Resend

**Comment by Aloso** [comment] 2024-05-01 22:33
You might find this post insightful: [GitHub stale bot consindered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by Aloso** [comment] 2024-06-01 19:35
what should I comment

**Comment by andris9** [comment] 2024-06-01 19:43
Nodemailer is not compatible with Cloudflare functions. This is because the required net and tls modules do not work with Cloudflare.

**Closed by andris9** 2024-06-01 19:43 UTC
Labels: no-issue-activity

**Comment by sheecegardezi** [comment] 2024-06-02 15:32
@andris9 I think they are available now! Is it poosible to get a very small toy code to import net and tls and print out soem random varibles from these libries just to check that they are improted corretly? I can do an experiment to try and get them to work.

**Comment by bitofbreeze** [comment] 2024-08-24 21:52
Here's a list of all the instances that need to be prefixed to work in workerd. Everything is available, so this seems like a simple task to make it compatible.

```

23:47:48.344 | ✘ [ERROR] 51 error(s) and 0 warning(s) when compiling Worker.
-- | --
23:47:48.344 |  
23:47:48.344 |  
23:47:48.347 |  
23:47:48.352 | ✘ [ERROR] Could not resolve "stream"
23:47:48.352 |  
23:47:48.352 | ../node_modules/nodemailer/lib/base64/index.js:3:26:
23:47:48.352 | 3 │ const Transform = require('stream').Transform;
23:47:48.353 | ╵                           ~~~~~~~~
23:47:48.353 |  
23:47:48.353 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.353 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.353 |  
23:47:48.354 |  
23:47:48.354 | ✘ [ERROR] Could not resolve "stream"
23:47:48.354 |  
23:47:48.354 | ../node_modules/nodemailer/lib/dkim/index.js:9:28:
23:47:48.355 | 9 │ const PassThrough = require('stream').PassThrough;
23:47:48.355 | ╵                             ~~~~~~~~
23:47:48.355 |  
23:47:48.355 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.356 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.356 |  
23:47:48.356 |  
23:47:48.356 | ✘ [ERROR] Could not resolve "fs"
23:47:48.356 |  
23:47:48.356 | ../node_modules/nodemailer/lib/dkim/index.js:10:19:
23:47:48.356 | 10 │ const fs = require('fs');
23:47:48.356 | ╵                    ~~~~
23:47:48.356 |  
23:47:48.357 | The package "fs" wasn't found on the file system but is built into node.
23:47:48.357 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.357 |  
23:47:48.357 |  
23:47:48.357 | ✘ [ERROR] Could not resolve "path"
23:47:48.357 |  
23:47:48.357 | ../node_modules/nodemailer/lib/dkim/index.js:11:21:
23:47:48.357 | 11 │ const path = require('path');
23:47:48.357 | ╵                      ~~~~~~
23:47:48.357 |  
23:47:48.357 | The package "path" wasn't found on the file system but is built into node.
23:47:48.358 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.358 |  
23:47:48.358 |  
23:47:48.358 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.358 |  
23:47:48.358 | ../node_modules/nodemailer/lib/dkim/index.js:12:23:
23:47:48.358 | 12 │ const crypto = require('crypto');
23:47:48.359 | ╵                        ~~~~~~~~
23:47:48.359 |  
23:47:48.359 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.359 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.359 |  
23:47:48.359 |  
23:47:48.359 | ✘ [ERROR] Could not resolve "stream"
23:47:48.359 |  
23:47:48.360 | ../node_modules/nodemailer/lib/dkim/message-parser.js:3:26:
23:47:48.360 | 3 │ const Transform = require('stream').Transform;
23:47:48.360 | ╵                           ~~~~~~~~
23:47:48.360 |  
23:47:48.360 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.361 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.361 |  
23:47:48.361 |  
23:47:48.361 | ✘ [ERROR] Could not resolve "stream"
23:47:48.361 |  
23:47:48.362 | ../node_modules/nodemailer/lib/dkim/relaxed-body.js:5:26:
23:47:48.362 | 5 │ const Transform = require('stream').Transform;
23:47:48.362 | ╵                           ~~~~~~~~
23:47:48.362 |  
23:47:48.362 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.362 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.362 |  
23:47:48.362 |  
23:47:48.362 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.363 |  
23:47:48.363 | ../node_modules/nodemailer/lib/dkim/relaxed-body.js:6:23:
23:47:48.363 | 6 │ const crypto = require('crypto');
23:47:48.363 | ╵                        ~~~~~~~~
23:47:48.363 |  
23:47:48.363 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.363 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.363 |  
23:47:48.363 |  
23:47:48.363 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.364 |  
23:47:48.364 | ../node_modules/nodemailer/lib/dkim/sign.js:5:23:
23:47:48.364 | 5 │ const crypto = require('crypto');
23:47:48.364 | ╵                        ~~~~~~~~
23:47:48.364 |  
23:47:48.364 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.364 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.364 |  
23:47:48.364 |  
23:47:48.365 | ✘ [ERROR] Could not resolve "url"
23:47:48.365 |  
23:47:48.365 | ../node_modules/nodemailer/lib/fetch/cookies.js:5:23:
23:47:48.365 | 5 │ const urllib = require('url');
23:47:48.365 | ╵                        ~~~~~
23:47:48.365 |  
23:47:48.365 | The package "url" wasn't found on the file system but is built into node.
23:47:48.365 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.366 |  
23:47:48.366 |  
23:47:48.366 | ✘ [ERROR] Could not resolve "http"
23:47:48.366 |  
23:47:48.366 | ../node_modules/nodemailer/lib/fetch/index.js:3:21:
23:47:48.366 | 3 │ const http = require('http');
23:47:48.366 | ╵                      ~~~~~~
23:47:48.366 |  
23:47:48.367 | The package "http" wasn't found on the file system but is built into node.
23:47:48.367 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.367 |  
23:47:48.367 |  
23:47:48.367 | ✘ [ERROR] Could not resolve "https"
23:47:48.367 |  
23:47:48.367 | ../node_modules/nodemailer/lib/fetch/index.js:4:22:
23:47:48.367 | 4 │ const https = require('https');
23:47:48.368 | ╵                       ~~~~~~~
23:47:48.368 |  
23:47:48.368 | The package "https" wasn't found on the file system but is built into node.
23:47:48.368 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.368 |  
23:47:48.368 |  
23:47:48.368 | ✘ [ERROR] Could not resolve "url"
23:47:48.369 |  
23:47:48.369 | ../node_modules/nodemailer/lib/fetch/index.js:5:23:
23:47:48.369 | 5 │ const urllib = require('url');
23:47:48.369 | ╵                        ~~~~~
23:47:48.369 |  
23:47:48.369 | The package "url" wasn't found on the file system but is built into node.
23:47:48.370 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.370 |  
23:47:48.370 |  
23:47:48.370 | ✘ [ERROR] Could not resolve "zlib"
23:47:48.370 |  
23:47:48.370 | ../node_modules/nodemailer/lib/fetch/index.js:6:21:
23:47:48.370 | 6 │ const zlib = require('zlib');
23:47:48.370 | ╵                      ~~~~~~
23:47:48.370 |  
23:47:48.370 | The package "zlib" wasn't found on the file system but is built into node.
23:47:48.370 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.371 |  
23:47:48.371 |  
23:47:48.371 | ✘ [ERROR] Could not resolve "stream"
23:47:48.371 |  
23:47:48.371 | ../node_modules/nodemailer/lib/fetch/index.js:7:28:
23:47:48.371 | 7 │ const PassThrough = require('stream').PassThrough;
23:47:48.371 | ╵                             ~~~~~~~~
23:47:48.371 |  
23:47:48.371 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.372 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.372 |  
23:47:48.372 |  
23:47:48.372 | ✘ [ERROR] Could not resolve "net"
23:47:48.372 |  
23:47:48.372 | ../node_modules/nodemailer/lib/fetch/index.js:10:20:
23:47:48.372 | 10 │ const net = require('net');
23:47:48.372 | ╵                     ~~~~~
23:47:48.372 |  
23:47:48.372 | The package "net" wasn't found on the file system but is built into node.
23:47:48.372 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.373 |  
23:47:48.373 |  
23:47:48.373 | ✘ [ERROR] Could not resolve "events"
23:47:48.373 |  
23:47:48.373 | ../node_modules/nodemailer/lib/mailer/index.js:3:29:
23:47:48.373 | 3 │ const EventEmitter = require('events');
23:47:48.373 | ╵                              ~~~~~~~~
23:47:48.373 |  
23:47:48.374 | The package "events" wasn't found on the file system but is built into node.
23:47:48.374 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.374 |  
23:47:48.374 |  
23:47:48.374 | ✘ [ERROR] Could not resolve "url"
23:47:48.374 |  
23:47:48.374 | ../node_modules/nodemailer/lib/mailer/index.js:10:23:
23:47:48.375 | 10 │ const urllib = require('url');
23:47:48.375 | ╵                        ~~~~~
23:47:48.375 |  
23:47:48.375 | The package "url" wasn't found on the file system but is built into node.
23:47:48.375 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.375 |  
23:47:48.375 |  
23:47:48.375 | ✘ [ERROR] Could not resolve "net"
23:47:48.375 |  
23:47:48.375 | ../node_modules/nodemailer/lib/mailer/index.js:13:20:
23:47:48.375 | 13 │ const net = require('net');
23:47:48.376 | ╵                     ~~~~~
23:47:48.376 |  
23:47:48.376 | The package "net" wasn't found on the file system but is built into node.
23:47:48.376 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.376 |  
23:47:48.376 |  
23:47:48.376 | ✘ [ERROR] Could not resolve "dns"
23:47:48.376 |  
23:47:48.376 | ../node_modules/nodemailer/lib/mailer/index.js:14:20:
23:47:48.376 | 14 │ const dns = require('dns');
23:47:48.377 | ╵                     ~~~~~
23:47:48.377 |  
23:47:48.377 | The package "dns" wasn't found on the file system but is built into node.
23:47:48.377 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.377 |  
23:47:48.377 |  
23:47:48.377 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.377 |  
23:47:48.377 | ../node_modules/nodemailer/lib/mailer/index.js:15:23:
23:47:48.377 | 15 │ const crypto = require('crypto');
23:47:48.377 | ╵                        ~~~~~~~~
23:47:48.377 |  
23:47:48.378 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.378 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.378 |  
23:47:48.378 |  
23:47:48.378 | ✘ [ERROR] Could not resolve "path"
23:47:48.378 |  
23:47:48.378 | ../node_modules/nodemailer/lib/mime-funcs/mime-types.js:5:21:
23:47:48.378 | 5 │ const path = require('path');
23:47:48.378 | ╵                      ~~~~~~
23:47:48.378 |  
23:47:48.379 | The package "path" wasn't found on the file system but is built into node.
23:47:48.379 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.381 |  
23:47:48.381 |  
23:47:48.381 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.381 |  
23:47:48.381 | ../node_modules/nodemailer/lib/mime-node/index.js:5:23:
23:47:48.381 | 5 │ const crypto = require('crypto');
23:47:48.381 | ╵                        ~~~~~~~~
23:47:48.381 |  
23:47:48.381 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.381 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.381 |  
23:47:48.381 |  
23:47:48.381 | ✘ [ERROR] Could not resolve "fs"
23:47:48.381 |  
23:47:48.381 | ../node_modules/nodemailer/lib/mime-node/index.js:6:19:
23:47:48.381 | 6 │ const fs = require('fs');
23:47:48.381 | ╵                    ~~~~
23:47:48.381 |  
23:47:48.381 | The package "fs" wasn't found on the file system but is built into node.
23:47:48.381 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.381 |  
23:47:48.381 |  
23:47:48.381 | ✘ [ERROR] Could not resolve "stream"
23:47:48.381 |  
23:47:48.381 | ../node_modules/nodemailer/lib/mime-node/index.js:8:28:
23:47:48.381 | 8 │ const PassThrough = require('stream').PassThrough;
23:47:48.381 | ╵                             ~~~~~~~~
23:47:48.381 |  
23:47:48.381 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.381 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.382 |  
23:47:48.382 |  
23:47:48.382 | ✘ [ERROR] Could not resolve "stream"
23:47:48.382 |  
23:47:48.382 | ../node_modules/nodemailer/lib/mime-node/last-newline.js:3:26:
23:47:48.382 | 3 │ const Transform = require('stream').Transform;
23:47:48.382 | ╵                           ~~~~~~~~
23:47:48.382 |  
23:47:48.382 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.382 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.382 |  
23:47:48.382 |  
23:47:48.382 | ✘ [ERROR] Could not resolve "stream"
23:47:48.382 |  
23:47:48.383 | ../node_modules/nodemailer/lib/mime-node/le-unix.js:3:23:
23:47:48.383 | 3 │ const stream = require('stream');
23:47:48.383 | ╵                        ~~~~~~~~
23:47:48.383 |  
23:47:48.383 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.383 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.383 |  
23:47:48.383 |  
23:47:48.383 | ✘ [ERROR] Could not resolve "stream"
23:47:48.383 |  
23:47:48.383 | ../node_modules/nodemailer/lib/mime-node/le-windows.js:3:23:
23:47:48.383 | 3 │ const stream = require('stream');
23:47:48.384 | ╵                        ~~~~~~~~
23:47:48.384 |  
23:47:48.384 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.384 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.384 |  
23:47:48.384 |  
23:47:48.384 | ✘ [ERROR] Could not resolve "stream"
23:47:48.384 |  
23:47:48.384 | ../node_modules/nodemailer/lib/qp/index.js:3:26:
23:47:48.384 | 3 │ const Transform = require('stream').Transform;
23:47:48.384 | ╵                           ~~~~~~~~
23:47:48.385 |  
23:47:48.385 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.385 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.385 |  
23:47:48.385 |  
23:47:48.385 | ✘ [ERROR] Could not resolve "child_process"
23:47:48.385 |  
23:47:48.385 | ../node_modules/nodemailer/lib/sendmail-transport/index.js:3:22:
23:47:48.385 | 3 │ const spawn = require('child_process').spawn;
23:47:48.385 | ╵                       ~~~~~~~~~~~~~~~
23:47:48.385 |  
23:47:48.385 | The package "child_process" wasn't found on the file system but is built into node.
23:47:48.386 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.386 |  
23:47:48.386 |  
23:47:48.386 | ✘ [ERROR] Could not resolve "events"
23:47:48.386 |  
23:47:48.386 | ../node_modules/nodemailer/lib/ses-transport/index.js:3:29:
23:47:48.386 | 3 │ const EventEmitter = require('events');
23:47:48.386 | ╵                              ~~~~~~~~
23:47:48.386 |  
23:47:48.386 | The package "events" wasn't found on the file system but is built into node.
23:47:48.386 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.387 |  
23:47:48.387 |  
23:47:48.387 | ✘ [ERROR] Could not resolve "url"
23:47:48.387 |  
23:47:48.387 | ../node_modules/nodemailer/lib/shared/index.js:5:23:
23:47:48.387 | 5 │ const urllib = require('url');
23:47:48.387 | ╵                        ~~~~~
23:47:48.387 |  
23:47:48.387 | The package "url" wasn't found on the file system but is built into node.
23:47:48.387 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.387 |  
23:47:48.388 |  
23:47:48.388 | ✘ [ERROR] Could not resolve "fs"
23:47:48.388 |  
23:47:48.388 | ../node_modules/nodemailer/lib/shared/index.js:7:19:
23:47:48.388 | 7 │ const fs = require('fs');
23:47:48.388 | ╵                    ~~~~
23:47:48.388 |  
23:47:48.388 | The package "fs" wasn't found on the file system but is built into node.
23:47:48.388 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.388 |  
23:47:48.388 |  
23:47:48.389 | ✘ [ERROR] Could not resolve "dns"
23:47:48.389 |  
23:47:48.389 | ../node_modules/nodemailer/lib/shared/index.js:9:20:
23:47:48.389 | 9 │ const dns = require('dns');
23:47:48.389 | ╵                     ~~~~~
23:47:48.389 |  
23:47:48.389 | The package "dns" wasn't found on the file system but is built into node.
23:47:48.389 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.389 |  
23:47:48.389 |  
23:47:48.389 | ✘ [ERROR] Could not resolve "net"
23:47:48.390 |  
23:47:48.390 | ../node_modules/nodemailer/lib/shared/index.js:10:20:
23:47:48.390 | 10 │ const net = require('net');
23:47:48.390 | ╵                     ~~~~~
23:47:48.390 |  
23:47:48.390 | The package "net" wasn't found on the file system but is built into node.
23:47:48.390 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.390 |  
23:47:48.390 |  
23:47:48.390 | ✘ [ERROR] Could not resolve "os"
23:47:48.390 |  
23:47:48.391 | ../node_modules/nodemailer/lib/shared/index.js:11:19:
23:47:48.391 | 11 │ const os = require('os');
23:47:48.391 | ╵                    ~~~~
23:47:48.391 |  
23:47:48.391 | The package "os" wasn't found on the file system but is built into node.
23:47:48.391 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.391 |  
23:47:48.391 |  
23:47:48.391 | ✘ [ERROR] Could not resolve "stream"
23:47:48.391 |  
23:47:48.391 | ../node_modules/nodemailer/lib/smtp-connection/data-stream.js:3:23:
23:47:48.391 | 3 │ const stream = require('stream');
23:47:48.392 | ╵                        ~~~~~~~~
23:47:48.392 |  
23:47:48.392 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.392 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.392 |  
23:47:48.392 |  
23:47:48.392 | ✘ [ERROR] Could not resolve "net"
23:47:48.392 |  
23:47:48.392 | ../node_modules/nodemailer/lib/smtp-connection/http-proxy-client.js:7:20:
23:47:48.392 | 7 │ const net = require('net');
23:47:48.393 | ╵                     ~~~~~
23:47:48.393 |  
23:47:48.393 | The package "net" wasn't found on the file system but is built into node.
23:47:48.393 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.393 |  
23:47:48.393 |  
23:47:48.393 | ✘ [ERROR] Could not resolve "tls"
23:47:48.393 |  
23:47:48.393 | ../node_modules/nodemailer/lib/smtp-connection/http-proxy-client.js:8:20:
23:47:48.393 | 8 │ const tls = require('tls');
23:47:48.393 | ╵                     ~~~~~
23:47:48.394 |  
23:47:48.394 | The package "tls" wasn't found on the file system but is built into node.
23:47:48.394 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.394 |  
23:47:48.394 |  
23:47:48.394 | ✘ [ERROR] Could not resolve "url"
23:47:48.394 |  
23:47:48.394 | ../node_modules/nodemailer/lib/smtp-connection/http-proxy-client.js:9:23:
23:47:48.394 | 9 │ const urllib = require('url');
23:47:48.394 | ╵                        ~~~~~
23:47:48.395 |  
23:47:48.395 | The package "url" wasn't found on the file system but is built into node.
23:47:48.395 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.395 |  
23:47:48.395 |  
23:47:48.395 | ✘ [ERROR] Could not resolve "events"
23:47:48.395 |  
23:47:48.395 | ../node_modules/nodemailer/lib/smtp-connection/index.js:4:29:
23:47:48.395 | 4 │ const EventEmitter = require('events').EventEmitter;
23:47:48.395 | ╵                              ~~~~~~~~
23:47:48.395 |  
23:47:48.395 | The package "events" wasn't found on the file system but is built into node.
23:47:48.396 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.396 |  
23:47:48.396 |  
23:47:48.396 | ✘ [ERROR] Could not resolve "net"
23:47:48.396 |  
23:47:48.396 | ../node_modules/nodemailer/lib/smtp-connection/index.js:5:20:
23:47:48.396 | 5 │ const net = require('net');
23:47:48.396 | ╵                     ~~~~~
23:47:48.396 |  
23:47:48.396 | The package "net" wasn't found on the file system but is built into node.
23:47:48.396 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.396 |  
23:47:48.397 |  
23:47:48.397 | ✘ [ERROR] Could not resolve "tls"
23:47:48.397 |  
23:47:48.397 | ../node_modules/nodemailer/lib/smtp-connection/index.js:6:20:
23:47:48.397 | 6 │ const tls = require('tls');
23:47:48.397 | ╵                     ~~~~~
23:47:48.397 |  
23:47:48.397 | The package "tls" wasn't found on the file system but is built into node.
23:47:48.397 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.397 |  
23:47:48.397 |  
23:47:48.398 | ✘ [ERROR] Could not resolve "os"
23:47:48.398 |  
23:47:48.398 | ../node_modules/nodemailer/lib/smtp-connection/index.js:7:19:
23:47:48.398 | 7 │ const os = require('os');
23:47:48.398 | ╵                    ~~~~
23:47:48.398 |  
23:47:48.398 | The package "os" wasn't found on the file system but is built into node.
23:47:48.398 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.398 |  
23:47:48.399 |  
23:47:48.399 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.399 |  
23:47:48.399 | ../node_modules/nodemailer/lib/smtp-connection/index.js:8:23:
23:47:48.399 | 8 │ const crypto = require('crypto');
23:47:48.399 | ╵                        ~~~~~~~~
23:47:48.399 |  
23:47:48.399 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.399 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.399 |  
23:47:48.400 |  
23:47:48.400 | ✘ [ERROR] Could not resolve "stream"
23:47:48.400 |  
23:47:48.400 | ../node_modules/nodemailer/lib/smtp-connection/index.js:10:28:
23:47:48.400 | 10 │ const PassThrough = require('stream').PassThrough;
23:47:48.400 | ╵                             ~~~~~~~~
23:47:48.400 |  
23:47:48.400 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.400 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.400 |  
23:47:48.400 |  
23:47:48.400 | ✘ [ERROR] Could not resolve "events"
23:47:48.401 |  
23:47:48.401 | ../node_modules/nodemailer/lib/smtp-pool/index.js:3:29:
23:47:48.401 | 3 │ const EventEmitter = require('events');
23:47:48.401 | ╵                              ~~~~~~~~
23:47:48.401 |  
23:47:48.401 | The package "events" wasn't found on the file system but is built into node.
23:47:48.401 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.401 |  
23:47:48.401 |  
23:47:48.401 | ✘ [ERROR] Could not resolve "events"
23:47:48.401 |  
23:47:48.401 | ../node_modules/nodemailer/lib/smtp-pool/pool-resource.js:6:29:
23:47:48.402 | 6 │ const EventEmitter = require('events');
23:47:48.402 | ╵                              ~~~~~~~~
23:47:48.402 |  
23:47:48.402 | The package "events" wasn't found on the file system but is built into node.
23:47:48.402 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.402 |  
23:47:48.402 |  
23:47:48.402 | ✘ [ERROR] Could not resolve "events"
23:47:48.402 |  
23:47:48.402 | ../node_modules/nodemailer/lib/smtp-transport/index.js:3:29:
23:47:48.402 | 3 │ const EventEmitter = require('events');
23:47:48.403 | ╵                              ~~~~~~~~
23:47:48.403 |  
23:47:48.403 | The package "events" wasn't found on the file system but is built into node.
23:47:48.403 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.403 |  
23:47:48.403 |  
23:47:48.403 | ✘ [ERROR] Could not resolve "stream"
23:47:48.403 |  
23:47:48.404 | ../node_modules/nodemailer/lib/xoauth2/index.js:3:23:
23:47:48.404 | 3 │ const Stream = require('stream').Stream;
23:47:48.404 | ╵                        ~~~~~~~~
23:47:48.404 |  
23:47:48.404 | The package "stream" wasn't found on the file system but is built into node.
23:47:48.404 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.
23:47:48.404 |  
23:47:48.404 |  
23:47:48.404 | ✘ [ERROR] Could not resolve "crypto"
23:47:48.404 |  
23:47:48.404 | ../node_modules/nodemailer/lib/xoauth2/index.js:5:23:
23:47:48.405 | 5 │ const crypto = require('crypto');
23:47:48.405 | ╵                        ~~~~~~~~
23:47:48.405 |  
23:47:48.405 | The package "crypto" wasn't found on the file system but is built into node.
23:47:48.405 | Add the "nodejs_compat" compatibility flag to your Pages project and make sure to prefix the module name with "node:" to enable Node.js compatibility.

```

**Comment by elvisdurmishi** [comment] 2024-09-13 22:03
Still no updates on this right?

**Comment by Funshyaj** [comment] 2024-10-01 03:31
no Solution to this yet??

**Comment by SZOKOZ** [comment] 2024-10-11 17:25
There probably won't be real support for packages like these in the near future. However there are workarounds which Cloudflare describe here; [Send Emails With Postmark](https://developers.cloudflare.com/workers/tutorials/send-emails-with-postmark) and [Send Emails With Resend](https://developers.cloudflare.com/workers/tutorials/send-emails-with-resend)
