### ISSUE TITLE
Invalid login: 535-5.7.8 Username and Password not accepted. 

### ISSUE THREAD

**Issue by shiladityab24** [nodemailer/nodemailer#1167] opened 2020-07-20 06:20 UTC
facing issue from this line in app.js file:
  
`let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true, // true for 465, false for other ports
    auth: {
        user: '****@gmail.com', 
        pass: '*****'  
    },
    tls:{
      rejectUnauthorized:false
    }
  });`

and giving an error in the terminal 

Server started...
{ Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials s68sm6561971pjb.38 - gsmtp
    at SMTPConnection._formatError (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
    at SMTPConnection._responseActions.push.str (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:550:26)
    at SMTPConnection._processResponse (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
    at SMTPConnection._onData (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData.chunk (/home/rupb/Desktop/nodemail/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
  code: 'EAUTH',
  response:
   '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials s68sm6561971pjb.38 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN' }

My email id and password is correct but still facing this error.

**Comment by ykgautam09** [comment] 2020-07-25 12:10
did you allowed less secure app to connect on your google account

**Comment by nbroeking** [comment] 2020-07-25 18:27
Hey @shiladityab24 I think this is by design. Its not an issue with nodemailer but with how the gmail api works. 

Check out enabling insecure apps and app passwords for gmail. 

you may find this link helpful. - https://community.nodemailer.com/using-gmail/

**Comment by shiladityab24** [comment] 2020-07-25 18:40
> Hey @shiladityab24 I think this is by design. Its not an issue with nodemailer but with how the gmail api works.
> 
> Check out enabling insecure apps and app passwords for gmail.
> 
> you may find this link helpful. - https://community.nodemailer.com/using-gmail/

By oauth2 it is working.I have used this format
auth: {
    type: 'OAuth2',
    user: serverConfig.gmail.client_user,
    clientId: serverConfig.gmail.client_id,
    clientSecret: serverConfig.gmail.secret,
    refreshToken: serverConfig.gmail.refresh_token,
    accessToken: serverConfig.gmail.access_token,
  },

**Comment by shiladityab24** [comment] 2020-07-25 18:49
I dont know why it is not working with email and password, anyways from now onwards I have to use oauth for nodemailer

**Comment by andris9** [comment] 2020-07-29 08:36
Closing, this is a Gmail problem, not a Nodemailer issue

**Closed by andris9** 2020-07-29 08:36 UTC

**Comment by prasanna-col** [comment] 2023-02-07 08:33
> tls:{ rejectUnauthorized:false }

Did you get a solution for this issue?
