### ISSUE TITLE
It is giving Error: Invalid status code 500

### ISSUE THREAD

**Issue by gangaswamy** [nodemailer/nodemailer#1141] opened 2020-05-17 14:10 UTC
Error: Invalid status code 500
    at ClientRequest.<anonymous> (c:\data\projects\newencole\node_modules\nodemailer\lib\fetch\index.js:221:23)
    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user'
}

**Comment by goyney** [comment] 2020-05-17 16:20
I would like to chime in here that we are also now seeing this issue. It seems to have just started happening within the past 24 hours or so. Every time we try to create a test account, we get a 500 error.

Here's our helper function to generate the account:
```js
const createTestSmtpAccount = () => {
  return new Promise((resolve, reject) => {
    nodemailer.createTestAccount((error, account) => {
      if (error) {
        return reject(`Failed to create a testing account. Details: ${error.message}`);
      }
      return resolve({
        host: account.smtp.host,
        password: account.pass,
        port: account.smtp.port,
        secure: account.smtp.secure,
        username: account.user
      });
    });
  });
};
```

Using that always returns:
```
Error: Invalid status code 500
    at ClientRequest.req.on.res (node_modules/nodemailer/lib/fetch/index.js:221:23)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
```

The supplied code has been in use for quite some time and this just started happening, as I said, probably within the last 24 hours or so. We've done some intensive digging to make sure our enviornment hasn't changed, but found nothing. Additionally, running it locally gives the same output.

We also checked to see if Ethereal was having issues, but they have not reported anything on their status page: https://status.ethereal.email/

**Comment by goyney** [comment] 2020-05-17 16:24
Duplicate of #1140.

**Comment by andris9** [comment] 2020-05-17 18:36
Fixed now

**Closed by andris9** 2020-05-17 18:36 UTC
