### ISSUE TITLE
What does it do with 'https://api.nodemailer.com/user'

### ISSUE THREAD

**Issue by StevenWung** [nodemailer/nodemailer#1139] opened 2020-05-17 01:50 UTC
When I am trying to send email with nodemailer, I got an error **Invalid status code 500**

The detailed error shows a request to 'sourceUrl: "https://api.nodemailer.com/user"'
I am wondering, why nodemailer has to connect to host **api.nodemailer.com**?

**Comment by goyney** [comment] 2020-05-17 16:24
Duplicate of #1140.

**Comment by andris9** [comment] 2020-05-17 18:37
Fixed now

**Closed by andris9** 2020-05-17 18:37 UTC
